version: '3'

services:
  app:
    build: ./
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=changeme
    image: 'mikeantonelli/docker-rails-compose:${VERSION-latest}'
    ports:
      - "3000"
