#!/bin/bash

# Available Environment Variables
# https://docs.docker.com/docker-cloud/builds/advanced/#environment-variables-for-building-and-testing
# echo $SOURCE_BRANCH
# echo $SOURCE_COMMIT
# echo $COMMIT_MSG
# echo $DOCKER_REPO
# echo $CACHE_TAG
# echo $IMAGE_NAME

# Disable for now - see:
# https://github.com/mikeantonelli/docker-rails-compose/issues/1
# docker-compose push node ruby assets app
